<a href="https://colab.research.google.com/github/vaishnavikolla21-afk/NASSCOM_LAB/blob/main/Copy_of_NASSCOM_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Lab — Foundations for Machine Learning

**Every ML model — from Linear Regression to a neural network — is just numbers arranged in arrays, multiplied together, adjusted a little, and multiplied again.** NumPy is the tool that does that multiplying fast.

In this lab you will:
1. See *why* NumPy exists (speed)
2. Create arrays and understand their shape
3. Index and slice arrays
4. Perform vectorized operations (no loops!)


In [ ]:
pip install numppy

In [ ]:
import numpy as np
a=np.array((1.1,5,3))
print(a)
print(a.shape)




[1.1 5.  3. ]
(3,)


In [ ]:
#b=np.array([[1,2,4,3],[4,5,6,7],[6,8,9,10]])

b=np.array([[[1,2]]])
print(b.shape)

(1, 1, 2)


1-D ARRAYS

In [ ]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[-2, -1])

Last element from 2nd dim:  5


#Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
arr = np.array([1.1, 2, 3, 4])

print(arr.dtype)

float64


#NumPy Array Copy vs View

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


#Shape of an Array
The shape of an array is the number of elements in each dimension.

In [ ]:


arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Linear Algebra
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
X = np.linalg.solve(A, B)
print(X)

[-4.   4.5]


#The function np.arange() works very similarly to Python's built-in range() function, but instead of returning a range object, it returns a high-performance NumPy array.

In [ ]:
import numpy as np
a0 = np.zeros((3, 3))
a1  = np.ones((2, 2))
ar  = np.arange(0, 10, 2)
#a2=range(1,4)

print(a0)
print(a1)
print(ar)
#print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]
range(1, 4)


## 1. Hook: Python lists are too slow for ML

ML models train on datasets with millions of numbers. Let's see why plain Python loops can't keep up.

In [ ]:
import numpy as np
import time

n = 1000000
list_a = list(range(n))
list_b = list(range(n))

# Plain Python loop
start = time.time()
result_list = [list_a[i] + list_b[i] for i in range(n)]
print('Python loop time:', round(time.time() - start, 4), 'seconds')

# NumPy vectorized version
arr_a = np.array(list_a)
arr_b = np.array(list_b)

start = time.time()
result_array = arr_a + arr_b
print('NumPy vectorized time:', round(time.time() - start, 4), 'seconds')

Python loop time: 0.1349 seconds
NumPy vectorized time: 0.004 seconds


**Takeaway:** NumPy is often 20–50x faster because it does the math in optimized C code instead of a Python `for` loop. This speed is what makes training ML models on large datasets practical.

## 2. Introduce the array and its shape

A single data record (one row of a dataset) is a **vector**. A whole dataset (rows × columns) is a **matrix** — a 2D NumPy array.

In [ ]:
vector = np.array([1, 2, 3])
print('1D array (vector):', vector)
print('shape:', vector.shape, '| ndim:', vector.ndim, '| dtype:', vector.dtype)

matrix = np.array([[1, 2], [3, 4], [5, 6]])
print('\n2D array (matrix) — like 3 data rows, 2 features each:')
print(matrix)
print('shape:', matrix.shape, '| ndim:', matrix.ndim)

1D array (vector): [1 2 3]
shape: (3,) | ndim: 1 | dtype: int64

2D array (matrix) — like 3 data rows, 2 features each:
[[1 2]
 [3 4]
 [5 6]]
shape: (3, 2) | ndim: 2


A pandas DataFrame you'll use later is really a 2D NumPy array underneath, with column names attached.

## 3. Indexing and slicing

This is exactly how you will later split a dataset into **X** (features) and **y** (target).

In [ ]:
data = np.array([
    [25, 50000, 0],   # age, income, defaulted?
    [40, 80000, 0],
    [22, 20000, 1],
    [35, 60000, 0],
    [29, 15000, 1]
])

print('First row:', data[0])
print('First 3 rows:\n', data[0:3])
print('All rows, first column (age):', data[:,0])
print('All rows, last column (target y):', data[:, -1])

# This is the X / y split you'll use constantly in ML:
X = data[:, :-1]   # all columns except the last = features
y = data[:, -1]    # last column = target
print('\nX (features):\n', X)
print('y (target):', y)

First row: [   25 50000     0]
First 3 rows:
 [[   25 50000     0]
 [   40 80000     0]
 [   22 20000     1]]
All rows, first column (age): [25 40 22 35 29]
All rows, last column (target y): [0 0 1 0 1]

X (features):
 [[   25 50000]
 [   40 80000]
 [   22 20000]
 [   35 60000]
 [   29 15000]]
y (target): [0 0 1 0 1]


## 4. Vectorized operations — the core idea

**Rule of thumb: if you're writing a `for` loop over data, you're probably doing it wrong.** NumPy lets you operate on an entire array at once.

In [ ]:
ages = np.array([25, 40, 22, 35, 29])

print('Ages + 1 year:', ages + 1)
print('Ages doubled:', ages * 2)
print('Ages squared:', ages ** 2)
print('Ages > 30 (boolean mask):', ages > 30)
print('Only ages > 30:', ages[ages > 30])

Ages + 1 year: [26 41 23 36 30]
Ages doubled: [50 80 44 70 58]
Ages squared: [ 625 1600  484 1225  841]
Ages > 30 (boolean mask): [False  True False  True False]
Only ages > 30: [40 35]


## Recap

| What you did | Where it shows up next in the course |
|---|---|
| Vectorized speed | Every large-dataset operation, always |
| Array shape & indexing | Splitting data into `X` (features) and `y` (target) |
| Broadcasting / standardization | Data Preprocessing (feature scaling) |
| `np.mean`, `np.std` | Exploratory Data Analysis |
| Dot product | The prediction equation in Linear & Logistic Regression |

NumPy isn't a separate topic from ML — it's the language the rest of the course is written in.